### ISSUE TITLE
[dev.icinga.com #675] Implement a list of all scheduled downtimes, may be even with a Gantt chart

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-web#127]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/675

**Created by mfriedrich on 2010-08-04 07:16:58 +00:00**

Assignee: _mhein_
Status: _Resolved_  (closed on _2011-01-14 17:40:36 +00:00_)
Target Version: _1.3_
Last Update: _2011-01-14 17:40:36 +00:00 (in Redmine)_

---

http://feedback.icinga.org/forums/50329-general/suggestions/744560-implement-a-list-of-all-scheduled-downtimes?ref=title

**Changesets**

_2011-01-14 12:09:19 +00:00_ by _mhein_ d1e51e8f88d6aa7a009841ebf7600fb2ea38625c

    * Added downtime template (final, fixes #675)

---

**Relations**:

* relates [#675](https://dev.icinga.com/issues/675)

**Comment by ananthaa-advisory** [comment]
May I know how to list all the downtimes please. 

The /v1/objects/downtimes is not listing all the downtimes of services.
