### ISSUE TITLE
[dev.icinga.com #10955] redundant one-liner

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-web#1372]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10955

**Created by roberte on 2016-01-12 03:37:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-01-12 03:37:46 +00:00 (in Redmine)_

    Icinga Version: 1.11.1
    Icinga Web Version: 1.11.1
    IDO Version: 1.11.1
    OS Version: linux
    DB Type: PostgreSQL
    DB Version: 1
    Browser Version: 1

---

icinga-web/app/modules/AppKit/lib/database/models/NsmUser.php

the function \_\_updatePassword();
line two of this function seems redundant.

private function \_\_updatePassword($password) {
$this~~<span style="text-align:right;">user\_salt = $this</span>~~&gt;\_\_createSalt($this-&gt;user\_name);
hash\_hmac(self::HASH\_ALGO, $password, $this~~<span style="text-align:right;">user\_salt); // &lt;----------------</span>~~
$this~~<span style="text-align:right;">user\_password = hash\_hmac(self::HASH\_ALGO, $password, $this</span>~~&gt;user\_salt);
}

kthxbie

**Comment by dnsmichi** [comment]
Thx, but 1.x won't receive code quality patches anymore.
