### ISSUE TITLE
Hour picker shows Time HH:00:00

### ISSUE THREAD

**Issue by lasse-kristensen** [Icinga/icinga-web#1383]
Hey
Icinga Classic UI 1.14.0 (Backend 1.14.0) on CentOS release 6.8 (Final)

From the web UI, when i try to do a action where i can choose time(Re-schedule Next Service Check), it dont change time, when i drag the hour picker. Its just say: "Time HH:00:00".
The minute picker works fine.

![icinga hour picker](https://cloud.githubusercontent.com/assets/5700049/23165426/5904d87a-f83c-11e6-97b1-8390b4dc393e.JPG)

**Comment by dnsmichi** [comment]
Can you create a new issue in icinga/icinga-core please? That's where Classic UI issues are handled, this tracker is for Icinga Web 1.x.
