### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by Daxten** [Icinga/icinga-web#1385]
I just tested icinga using the docker container and had some weird mysql cpu times, see here:

![image](https://user-images.githubusercontent.com/1048786/28926048-f1ec7d0e-7866-11e7-8421-69bb868ec626.png)

is this expected behaviour or a bug? Icinga was only monitoring the host machine and was set to default everywhere

**Comment by dnsmichi** [comment]
Icinga 1.x is known to not scale and hog the cpu. Wrong tracker btw.
