### ISSUE TITLE
How to add new remote server(centos) Using interface ?

### ISSUE THREAD

**Issue by noreddineelga** [Icinga/icinga-web#1386]
I am using icinga 1.8 and mysql database.

I just install icinga and icinga-web, I can get the dashboard of icinga-web.
My goal is to monitor my remote servers, The problem is that i don't know how to do it ?
Thanks for your help.

**Comment by dnsmichi** [comment]
Edit your icinga configuration by hand or use an 1.x config tool. I'd suggest to look into 2.x as a better future alternative - https://www.icinga.com/docs
