### ISSUE TITLE
[dev.icinga.com #2586] Web path / not working

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga-web#773]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/2586

**Created by omula on 2012-05-07 07:55:07 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2015-04-26 07:42:40 +00:00_)
Target Version: _(none)_
Last Update: _2015-04-26 07:42:40 +00:00 (in Redmine)_

    Icinga Version: 1.6.1
    Icinga Web Version: 1.6.1
    IDO Version: 1.6.1
    OS Version: Debian 6
    DB Type: MySQL
    DB Version: 5.1
    Browser Version: any

---

Setting the configure option --with-web-path to / makes icinga-web not to work.

In this case if appkit.web\_path is equal to / or left empty icinga-web fails to work.

---

**Relations**:

* blocks [#2586](https://dev.icinga.com/issues/2586)

**Comment by vickynamdeo** [comment]
Hi,
I just install icinga 1.10.0 . My icinga is running but i am not able to see styles and js/ext3.
both are present in directory .while i troubleshoot throuh the devloper tool then files are shoing in styles but after click on that file no output comes .
1- image for the Style 
![image](https://cloud.githubusercontent.com/assets/25272253/22178491/b8560624-e05d-11e6-9712-71e1b613793e.png)
2- for the js/ext3
![image](https://cloud.githubusercontent.com/assets/25272253/22178493/c9ba3188-e05d-11e6-8edf-d660e1f97100.png)
3- <Directory /opt/foss/icinga-web/pub>
index.php proply .

![image](https://cloud.githubusercontent.com/assets/25272253/22178495/e248b828-e05d-11e6-85e1-77b5e1d639aa.png)


# **this is the icinga-web.conf**


# Icinga Web Apache configuration
#
# this file includes all RewriteRules required
#
# No .htaccess file is needed under
# the application paths.
#
# (c) 2012 Icinga Development Team
# Markus Frosch <markus@lazyfrosch.de>
###

# Matching for module stylesheet and images
AliasMatch /icinga-web/modules/([A-Za-z0-9]*)/resources/styles/([A-Za-z0-9]*\.css)$ /opt/foss/icinga-web/app/modules/$1/pub/styles/$2
AliasMatch /icinga-web/modules/([A-Za-z0-9]*)/resources/images/([A-Za-z_\-0-9]*\.(png|gif|jpg))$ /opt/foss/icinga-web/app/modules/$1/pub/images/$2


# Matching for Icinga Web and the ext3 framework
Alias /icinga-web/js/ext3 /opt/foss/icinga-web/lib/ext3

Alias /icinga-web /opt/foss/icinga-web/pub

#RedirectMatch "^/icinga-web$" /icinga-web/

# Access to where the styles are located
<DirectoryMatch /opt/foss/icinga-web/app/modules/\w+/pub/styles/>
 Options -Indexes -MultiViews
 Require all granted
</DirectoryMatch>

# Access to where the images are located
<DirectoryMatch /opt/foss/icinga-web/app/modules/\w+/pub/images/>
    Options -Indexes -MultiViews
    Require all granted
</DirectoryMatch>

# Access to the ext3 library
<Directory /opt/foss/icinga-web/lib/ext3>
    Options -Indexes -MultiViews
   Require all granted
</Directory>

# Access to the public web folder of Icinga Web
<Directory /opt/foss/icinga-web/pub>
    DirectoryIndex index.php
    Options FollowSymLinks
    Require all granted
    Options -MultiViews -Indexes +FollowSymLinks

    RewriteEngine On
    # /icinga-web is base for all rewrite rules

    RewriteBase /icinga-web

    # If the requested URL does not exist (it's likely an agavi route),
    # pass it as path info to index.php, the Agavi dispatch script.

    RewriteRule ^$ index.php?/ [QSA,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule (.*) index.php?/$1 [QSA,L]

    <IfModule mod_deflate.c>
        # Insert filter
        SetOutputFilter DEFLATE

        # Netscape 4.x has some problems...
        BrowserMatch ^Mozilla/4 gzip-only-text/html

        # Netscape 4.06-4.08 have some more problems
        BrowserMatch ^Mozilla/4\.0[678] no-gzip

        # MSIE masquerades as Netscape, but it is fine
        BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        # Don't compress images
        SetEnvIfNoCase Request_URI \
        \.(?:gif|jpe?g|png)$ no-gzip dont-vary

        # Make sure proxies don't deliver the wrong content
        <IfModule mod_headers.c>
            Header append Vary User-Agent env=!dont-vary
        </IfModule>
    </IfModule>

    <IfDefine APACHE2>
        AcceptPathInfo On
    </IfDefine>
</Directory>

..

icinga-web.conf included in httpd.conf also .

i m attaching the icnga home page ..
![image](https://cloud.githubusercontent.com/assets/25272253/22178520/a588dfc0-e05e-11e6-8248-d4d14757690d.png)

![image](https://cloud.githubusercontent.com/assets/25272253/22178528/c26c408c-e05e-11e6-8398-0cba3f8e35f9.png)


Please help me out .

Thanks
Kaushalendra Namdeo
+918287131273
vicky.namdeo@gmail.com
